# -*- coding: utf-8 -*-
"""q7_isaque_oficial_1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1iBOy474wFB4xfOPoj5VTPGfKnTPDBba5
"""

import PIL

from PIL import Image
img = Image.open('q7.jpg')

#criar Thumbnail

size = (200, 200)
img.thumbnail(size)
img.save('thumbnail.jpg')
print(image.thumbnail) 